name: Xcode Project
on: [push, workflow_dispatch]

jobs:
  ios:
    name: iOS
    runs-on: macOS-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build iOS
      run: |
        xcodebuild -project Stylizer.xcodeproj -scheme "Stylizer" -destination "generic/platform=iOS" -configuration Debug

    - name: Build iOS Simulator
      run: |
        xcodebuild -project Stylizer.xcodeproj -scheme "Stylizer" -destination "generic/platform=iOS Simulator" -configuration Debug

    - name: Test
      run: |
        xcodebuild -project Stylizer.xcodeproj -scheme "Stylizer" -testPlan "StylizerTests" -destination "platform=iOS Simulator,name=iPhone 12 Pro Max" -configuration Debug ONLY_ACTIVE_ARCH=YES test

  maccatalyst:
    name: Mac Catalyst
    runs-on: macOS-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build
      run: |
        xcodebuild -project Stylizer.xcodeproj -scheme "Stylizer" -destination "generic/platform=macOS,variant=Mac Catalyst" -configuration Debug

    - name: Test
      run: |
        xcodebuild -project Stylizer.xcodeproj -scheme "Stylizer" -testPlan "StylizerTests" -destination "platform=macOS,variant=Mac Catalyst" -configuration Debug ONLY_ACTIVE_ARCH=YES test

  macos:
    name: macOS
    runs-on: macOS-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build
      run: |
        xcodebuild -project Stylizer.xcodeproj -scheme "Stylizer macOS" -destination "generic/platform=macOS" -configuration Debug

    - name: Test
      run: |
        xcodebuild -project Stylizer.xcodeproj -scheme "Stylizer macOS" -testPlan "Stylizer macOS Tests" -configuration Debug test

  tvos:
    name: tvOS
    runs-on: macOS-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build tvOS
      run: |
        xcodebuild -project Stylizer.xcodeproj -scheme "Stylizer tvOS" -destination "generic/platform=tvOS" -configuration Debug

    - name: Build tvOS Simulator
      run: |
        xcodebuild -project Stylizer.xcodeproj -scheme "Stylizer tvOS" -destination "generic/platform=tvOS Simulator" -configuration Debug

    - name: Test
      run: |
        xcodebuild -project Stylizer.xcodeproj -scheme "Stylizer tvOS" -testPlan "Stylizer tvOS Tests" -destination "platform=tvOS Simulator,name=Apple TV 4K" -configuration Debug ONLY_ACTIVE_ARCH=YES test

  watchos:
    name: watchOS
    runs-on: macOS-11

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build watchOS
      run: |
        xcodebuild -project Stylizer.xcodeproj -scheme "Stylizer watchOS" -destination "generic/platform=watchOS" -configuration Debug

    - name: Build watchOS Simulator
      run: |
        xcodebuild -project Stylizer.xcodeproj -scheme "Stylizer watchOS" -destination "generic/platform=watchOS Simulator" -configuration Debug

    - name: Test
      run: |
        xcodebuild -project Stylizer.xcodeproj -scheme "Stylizer watchOS" -testPlan "Stylizer watchOS Tests" -destination "platform=watchOS Simulator,name=Apple Watch Series 6 - 44mm" -configuration Debug ONLY_ACTIVE_ARCH=YES test
